[package]
name = "simple-storage-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.simple_storage]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.57.0"
default-features = false
