[package]
name = "crowdfunding"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
multiversx-sc = "0.57.0"

[dev-dependencies]
multiversx-sc-scenario = "0.57.0"
num-bigint = "0.4"
